[package]
name = "seekr"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "seek"
path = "src/main.rs"

[dependencies]
clap = "*"
rayon = "*"
ignore = "*"
regex = "*"
colored = "2.1.0"
log = "0.4.22"
num_cpus = "1.16.0"
tempfile = "3.13.0"
rlua = "0.20.1"
lazy_static = "1.5.0"
